application: spooglers-membership-db
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /javascript_files
  static_dir: javascript_files
- url: /.*
  script: main.app
  secure: always
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
  
inbound_services:
- mail
